"""Set function.name to not unique

Revision ID: 4d418c3e4274
Revises: 8085b781ccf2
Create Date: 2025-11-30 09:39:43.547313

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d418c3e4274"
down_revision: Union[str, Sequence[str], None] = "8085b781ccf2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_functions_name"), table_name="functions")
    op.create_index(op.f("ix_functions_name"), "functions", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_functions_name"), table_name="functions")
    op.create_index(op.f("ix_functions_name"), "functions", ["name"], unique=True)
    # ### end Alembic commands ###
